name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

    - name: Sonar Analysis
      run: |
         mvn clean verify sonar:sonar \
         -Dsonar.projectKey=realstate \
         -Dsonar.projectName='realstate' \
         -Dsonar.host.url=http://hivemet.com:9000 \
         -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Docker build of the realstate app
      run: |
        docker build -t mkumarda/realstateapp:1.0.0 .
        docker login -u mkumarda -p ${{ secrets.DOCKER_PASS }}
        docker push mkumarda/realstateapp:1.0.0

    - name: Connect to Kubernetes Cluster
      run: |
         cd kubernetes
         echo "${{secrets.ANSIBLE_VAULT_KEY}}" >> pass.yaml
         ansible-vault decrypt test.yaml --vault-password-file pass.yaml
         export KUBECONFIG=test.yaml
  
