name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

    - name: Docker build of the realstate app
      run: |
        docker build -t mkumarda/realstateapp:1.0.0 .
        docker login -u mkumarda -p ${{ secrets.DOCKER_PASS }}
        docker push mkumarda/realstateapp:1.0.0
  
